all: EscaleraFuerza EscaleraPd grafos MSCP

EscaleraFuerza: EscaleraFuerza.cpp
	g++ -o EscaleraFuerza EscaleraFuerza.cpp

EscaleraPd:EscaleraPd.cpp
	g++ -o EscaleraPd EscaleraPd.cpp

grafos:grafos.cpp
	g++ -o grafos grafos.cpp

MSCP: MSCP.cpp
	g++	-o MSCP MSCP.cpp

clean:
	rm -f EscaleraFuerza EscaleraPd grafos MSCP