all: EscaleraFuerza EscaleraPd

EscaleraFuerza: EscaleraFuerza.cpp
	g++ -o EscaleraFuerza EscaleraFuerza.cpp

EscaleraPd:EscaleraPd.cpp
	g++ -o EscaleraPd EscaleraPd.cpp

clean:
	rm -f EscaleraFuerza EscaleraPd.cpp
